### ISSUE TITLE
aws_s3 can't PUT when mandatory bucket-owner-full-control

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [ansible-collections/amazon.aws#219]
##### SUMMARY
I have a S3 bucket which I upload/download/delete objects from different AWS roles.  In order to achieve this, I upload files with the *'bucket-owner-full-control'* canned ACL.  I also make the use of the *'bucket-owner-full-control'* canned ACL mandatory from the bucket's end.

With all this in place, I can upload objects from command line using `aws s3api put-object` command, but upload fails with *Access Denied* when trying to do the same using Ansible's aws_s3 module.

Also note that the PUT operation using aws_s3 successes if I retire the *'bucket-owner-full-control'* condition from the bucket.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
amazon.aws.aws_s3

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.3
  config file = [REDACTED]/ansible/ansible.cfg
  configured module search path = ['[REDACTED]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = [REDACTED]/lib/python3.7/site-packages/ansible
  executable location = [REDACTED]/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING([REDACTED]/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES([REDACTED]/ansible/ansible.cfg) = 2
DEFAULT_LOAD_CALLBACK_PLUGINS([REDACTED]/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH([REDACTED]/ansible/ansible.cfg) = ['[REDACTED]/ansible/roles']
DEFAULT_STDOUT_CALLBACK([REDACTED]/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON([REDACTED]/ansible/ansible.cfg) = auto_silent
INVENTORY_UNPARSED_IS_FAILED([REDACTED]/ansible/ansible.cfg) = True
LOCALHOST_WARNING([REDACTED]/ansible/ansible.cfg) = False
VARIABLE_PRECEDENCE([REDACTED]/ansible/ansible.cfg) = ['all_plugins_play', 'groups_plugins_play', 'all_plugins_inventory', 'all_inventory', 'groups_plugins_inventory', 'groups_inventory']
```

##### OS / ENVIRONMENT

Working on a virtualenv, I don't think there're relevant info to put here.

##### STEPS TO REPRODUCE
bucket with policy (example; those are not the true ARNs, neither for principal nor for bucket):
```json
{
   "Version":"2012-10-17",
   "Statement":[
     {
       "Sid":"PolicyForAllowUploadWithACL",
       "Effect":"Allow",
       "Principal":{"AWS":"123456789012"},
       "Action":[
         "s3:PutObject",
         "s3:PutObjectAcl"
       ]
       "Resource":"arn:aws:s3:::DOC-EXAMPLE-BUCKET/*",
       "Condition": {
         "StringEquals": {"s3:x-amz-acl":"bucket-owner-full-control"}
       }
     }
   ]
}
```

This code fails:
```yaml
---
- name: Test AWS Lambda uploader
  hosts: localhost
  become: no
  gather_facts: no
  
  tasks:
  - name: Asumes required role to work against AWS
    sts_assume_role:
      region: "{{ aws_region }}"
      role_arn: "{{ aws_role_arn }}"
      role_session_name: "assumedRoleSession"
    register: assumed_role
    changed_when: False
    
  - name: Uploads lambda zip to S3
    aws_s3:
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      aws_security_token: "{{ assumed_role.sts_creds.session_token }}"
      region: "{{ aws_region }}"
      
      bucket: "{{ lambdas_bucket }}"
      src: "{{ lambdas_build_dir }}/{{ item.name }}.{{ item.version }}.zip"
      object: "lambdas/{{ item.name }}/{{ item.name }}.{{ item.version }}.zip"
      permission: bucket-owner-full-control
      overwrite: different
      mode: put
    loop: "{{ lambdas }}"
```
...but this code successes:
```yaml
---
- name: Test AWS Lambda uploader
  hosts: localhost
  become: no
  gather_facts: no
  
  tasks:
  - name: Asumes required role to work against AWS
    sts_assume_role:
      region: "{{ aws_region }}"
      role_arn: "{{ aws_role_arn }}"
      role_session_name: "assumedRoleSession"
    register: assumed_role
    changed_when: False
    
  - name: Uploads lambda zip to S3
    command: >-
      aws s3api put-object
        --bucket {{ lambdas_bucket }}
        --key lambdas/{{ item.name }}/{{ item.name }}.{{ item.version }}.zip
        --body {{ lambdas_build_dir }}/{{ item.name }}.{{ item.version }}.zip
        --acl bucket-owner-full-control
    environment:
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
      AWS_DEFAULT_REGION: "{{ aws_region }}"
    loop: "{{ lambdas }}"
```

Note that the code using the aws_s3 module also successes if I retire the *"s3:x-amz-acl":"bucket-owner-full-control"* condition from bucket.

##### EXPECTED RESULTS

PUT operation against S3 bucket to success.

##### ACTUAL RESULTS

I suspect the underlying *aws_s3* code is trying to *first* upload, *then* set permission and so, it fails, instead of doing it in one go.

```paste below
The full traceback is:
Traceback (most recent call last):
  File "[REDACTED]/lib/python3.7/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "[REDACTED]/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "[REDACTED]/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "[REDACTED]/lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "[REDACTED]/lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "[REDACTED]/lib/python3.7/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "[REDACTED]/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "[REDACTED]/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aws_s3_payload_6ro05161/ansible_aws_s3_payload.zip/ansible_collections/amazon/aws/plugins/modules/aws_s3.py", line 895, in <module>
  File "/tmp/ansible_aws_s3_payload_6ro05161/ansible_aws_s3_payload.zip/ansible_collections/amazon/aws/plugins/modules/aws_s3.py", line 800, in main
  File "/tmp/ansible_aws_s3_payload_6ro05161/ansible_aws_s3_payload.zip/ansible_collections/amazon/aws/plugins/modules/aws_s3.py", line 509, in upload_s3file
  File "[REDACTED]/lib/python3.7/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "[REDACTED]/lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload [REDACTED].zip to [REDACTED].zip: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied                                                                                                                                                                                                  
```

**Comment by tremble** [comment]
The issue here is that Ansible is doing the upload as a two-step process (upload the file, then set the ACL).  It looks like we need to update the code to add the ACL into ExtraArgs: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html#the-extraargs-parameter

Should someone have the time Pull Requests would be gratefully accepted, an integration test for this behaviour should also be added to the test suite.

**Comment by cbcoutinho** [comment]
I just ran into this bug as well, so I'm interested in tackling it. If I look at the current implementation of the `upload_s3file` method ([aws_s3.py#L514-L563](https://github.com/ansible-collections/amazon.aws/blob/045d70bb78753c98c969ee67bcbc5e034d0a7eed/plugins/modules/aws_s3.py#L514-L563)) I see that the ACLs are indeed added after the upload completes.

The problem with moving the ACLs to the `ExtraArgs` param is it will only accept a single "ACL" argument, whereas the `aws_s3` module accepts ACLs as either a single entry or a list. What does it mean to support a list of ACLs? In the current implementation, the `upload_s3file` method loops through each of the ACLs, applying them one after another. I assume that only the latest one is applied because I don't think objects can have multiple ACLs (e.g. `private` and `public-read` are mutually exclusive).

My point is, adding the ACL to the `ExtraArgs` in the `upload_file` and `upload_fileobj` method calls would require changing the current API of the `aws_s3` module to longer support lists of ACLs, which I consider a broken interpretation of S3 ACLs

**Comment by tremble** [comment]
Playing about a little, I believe it *is* possible to add multiple ACLs (after upload).

What I'd suggest is that you add the *first* entry from the list in ExtraArgs, and document that only the first argument is used during the initial upload and the others will be added after upload.

**Comment by cbcoutinho** [comment]
@tremble I created a PR based on your suggestions
