### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by D1StrX** [ansible-collections/amazon.aws#2264]
### Summary

When updating pip package `cryptography >= 42.0.0`, and `pyOpenSSL < 23.2.0`, Ansible will throw an error with (in my test) `amazon.aws.s3_object module`: 
```log
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

As explained here; https://github.com/conda/conda/issues/13619#issuecomment-2075825121
For folks curious about the breakage:

- cryptography 42.0.0 removed this X509_V_FLAG_NOTIFY_POLICY flag: https://github.com/pyca/cryptography/commit/654dccb8e9d26f4b95e19831f976fc53bef98544
- pyOpenSSL 23.2.0 stopped referencing this X509_V_FLAG_NOTIFY_POLICY flag: https://github.com/pyca/pyopenssl/commit/d788a4f1ee2cfe0642ea9e0533bb840077a88ca6

Installing the packages within these versions is a workaround. But the `X509_V_FLAG_NOTIFY_POLICY flag` should be removed.

### Issue Type

Bug Report

### Component Name

amazon.aws.s3_object module

### Ansible Version

ansible_core-2.15.12

### Collection Versions

'amazon.aws:8.1.0'

### AWS SDK versions

- 'botocore>=1.29.0  # from collection amazon.aws'
- 'boto3>=1.26.0  # from collection amazon.aws'

### OS / Environment

Ansible Execution Environment

### Steps to Reproduce

Run a playbook that uses the `amazon.aws.s3_object` module on an Ansible Execution Environment. The error is self explanatory. 

### Expected Results

Remove flag X509_V_FLAG_NOTIFY_POLICY flag.

### Actual Results

module_stderr: |
  Traceback (most recent call last):
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 107, in <module>
      _ansiballz_main()
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 99, in _ansiballz_main
      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 47, in invoke_module
      runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_object', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_object', _modlib_path=modlib_path),
    File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/tmp/ansible_amazon.aws.s3_object_payload_ye7c8w84/ansible_amazon.aws.s3_object_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_object.py", line 418, in <module>
    File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
      from boto3.session import Session
    File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
      import botocore.session
    File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
      import botocore.client
    File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 15, in <module>
      from botocore import waiter, xform_name
    File "/usr/local/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
      from botocore.docs.docstring import WaiterDocstring
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
      from botocore.docs.service import ServiceDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
      from botocore.docs.client import (
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/client.py", line 18, in <module>
      from botocore.docs.example import ResponseExampleDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
      from botocore.docs.shape import ShapeDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
      from botocore.utils import is_json_value_header
    File "/usr/local/lib/python3.9/site-packages/botocore/utils.py", line 39, in <module>
      import botocore.httpsession
    File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 45, in <module>
      from urllib3.contrib.pyopenssl import (
    File "/usr/local/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
      import OpenSSL.crypto
    File "/usr/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import crypto, SSL
    File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1579, in <module>
      class X509StoreFlags(object):
    File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
      NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
  AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
exception: |
  Traceback (most recent call last):
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 107, in <module>
      _ansiballz_main()
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 99, in _ansiballz_main
      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    File "/runner/.ansible/tmp/ansible-tmp-1724865178.8621795-113-147217989125914/AnsiballZ_s3_object.py", line 47, in invoke_module
      runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.s3_object', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.s3_object', _modlib_path=modlib_path),
    File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/tmp/ansible_amazon.aws.s3_object_payload_ye7c8w84/ansible_amazon.aws.s3_object_payload.zip/ansible_collections/amazon/aws/plugins/modules/s3_object.py", line 418, in <module>
    File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
      from boto3.session import Session
    File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
      import botocore.session
    File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
      import botocore.client
    File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 15, in <module>
      from botocore import waiter, xform_name
    File "/usr/local/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
      from botocore.docs.docstring import WaiterDocstring
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
      from botocore.docs.service import ServiceDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
      from botocore.docs.client import (
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/client.py", line 18, in <module>
      from botocore.docs.example import ResponseExampleDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
      from botocore.docs.shape import ShapeDocumenter
    File "/usr/local/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
      from botocore.utils import is_json_value_header
    File "/usr/local/lib/python3.9/site-packages/botocore/utils.py", line 39, in <module>
      import botocore.httpsession
    File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 45, in <module>
      from urllib3.contrib.pyopenssl import (
    File "/usr/local/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
      import OpenSSL.crypto
    File "/usr/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import crypto, SSL
    File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1579, in <module>
      class X509StoreFlags(object):
    File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
      NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
  AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
@D1StrX,

Thanks for taking the time to open this issue.

There's much we can do about this, it looks like it's just a problem with that specific combination of those libraries, neither of which we directly require or apply constraints to.  This was arguably a bug in pyOpenSSL which has already been fixed.

As such I'm going to close this issue.
